external_components:
  source:
    type: local
    path: ./components

ble_client:
  - mac_address: ${calima_device_mac}
    id: ${device_id}_ble

pax_calima:
  id: ${device_id}
  ble_client_id: ${device_id}_ble
  update_interval: 3min

fan:
  - platform: pax_calima
    id: ${device_id}_fan
    pax_calima_id: ${device_id}
    name: ${device_name} boost fan
    run_duration: 1h
               
sensor:
  - platform: pax_calima
    pax_calima_id: ${device_id}
    temperature:
      name: ${device_name} temperature
    humidity:
      name: ${device_name} humidity
    illuminance:
      name: ${device_name} illuminance
    rotation:
      name: ${device_name} rotation

text_sensor:
  - platform: pax_calima
    pax_calima_id: ${device_id}
    fan_mode:
      name: ${device_name} mode

switch:
  - platform: restart
    name: ${device_name} restart
