substitutions:
  device_name: "Vent-Axia Svara"
  device_id: "calima_fan"
  calima_device_mac: !secret device_mac

esphome:
  name: vent-axia-svara

esp32:
  board: nodemcu-32s
    
logger:
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
ota:

api:

web_server:

#esp32_ble_tracker:
#pax_calima_ble:

<<: !include .calima-base.yaml
