substitutions:
  device_name: "Pax Calima fan"
  device_id: "calima_fan"
  calima_device_mac: !secret device_mac
  calima_device_pin: !secret device_pin

esphome:
  name: vent-axia-svara

esp32:
  board: nodemcu-32s
    
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
ota:

api:

web_server:

# To find device MAC uncomment next two lines
#esp32_ble_tracker:
#pax_calima_ble:

<<: !include .calima-base.yaml
